language: minimal
os: linux
dist: focal

services:
  - docker

cache:
  directories:
    - docker_images

before_cache:
  - docker rmi $(docker images --filter "dangling=true" -q)
  - docker save $(docker images -a -q) | gzip -3 > docker_images/images.tar.gz

before_install:
  - docker load -i docker_images/images.tar.gz || true

install:
  - docker build -t dlshriver/dnnv .

script:
  - docker run dlshriver/dnnv /bin/bash -c '. .env.d/openenv.sh; coverage run'
